name: "Acknowledge ansible actions"
description: "Github actions used to run ansible playbook"
inputs:
  ansible_requirements_file:
    description: "Path to ansible requirements file for roles installation"
    required: false
    default: "requirements.yml"
  inventory:
    description: "Path to inventory file"
    required: true
    default: "inventory"
  playbook_file:
    description: "Path to playbook"
    required: true
    default: "site.yml"
  limit:
    description: "Define limit for ansible run"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "~/.local/bin" >> $GITHUB_PATH 
      shell: bash
    - run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py
        pip install ansible hvac
      shell: bash
    - run: ansible-galaxy install -r ${{ inputs.ansible_requirements_file }} -f
      shell: bash
    - run: ansible-playbook -i ${{ inputs.inventory }} --limit ${{ inputs.limit }} ${{ inputs.playbook_file }}
      shell: bash
